from typing import Union

def calculate_crypto_amount(fiat_amount: float, rate: float) -> float: ...

def calculate_fiat_amount(crypto_amount: float, rate: float) -> float: ...

def get_payment_url(payment_id: str) -> str: ...

def format_currency_amount(amount: Union[int, float], currency: str) -> str: ...
